// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65TYdZxDrj12oNvqPv_F-6th3YxcTxm0',
    appId: '1:34841424355:web:05c0ff19c86e23c6b2f0d6',
    messagingSenderId: '34841424355',
    projectId: 'connecthub-57eb5',
    authDomain: 'connecthub-57eb5.firebaseapp.com',
    storageBucket: 'connecthub-57eb5.firebasestorage.app',
    measurementId: 'G-VDH5NL5889',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33VF8yNIv5Jio3sS067SMTgpvGGALak0',
    appId: '1:34841424355:android:347083589d9f6e75b2f0d6',
    messagingSenderId: '34841424355',
    projectId: 'connecthub-57eb5',
    storageBucket: 'connecthub-57eb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRkTML-tcEuxKHs7IwfiMvsFmvxgTG-TU',
    appId: '1:34841424355:ios:554aaac20959c3aeb2f0d6',
    messagingSenderId: '34841424355',
    projectId: 'connecthub-57eb5',
    storageBucket: 'connecthub-57eb5.firebasestorage.app',
    iosBundleId: 'com.example.connecthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRkTML-tcEuxKHs7IwfiMvsFmvxgTG-TU',
    appId: '1:34841424355:ios:554aaac20959c3aeb2f0d6',
    messagingSenderId: '34841424355',
    projectId: 'connecthub-57eb5',
    storageBucket: 'connecthub-57eb5.firebasestorage.app',
    iosBundleId: 'com.example.connecthub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC65TYdZxDrj12oNvqPv_F-6th3YxcTxm0',
    appId: '1:34841424355:web:37959ee08b193d6eb2f0d6',
    messagingSenderId: '34841424355',
    projectId: 'connecthub-57eb5',
    authDomain: 'connecthub-57eb5.firebaseapp.com',
    storageBucket: 'connecthub-57eb5.firebasestorage.app',
    measurementId: 'G-0G91JY9VEM',
  );
}
